### ISSUE TITLE
Tutorial: This is an issue!

### ISSUE THREAD

**Issue by pixelyunicorn** [Team708/2015-Banshee#6]
Hey everyone!

This is an issue.
## Assignee

@lablayers
## Todo
- [x] Fork this repo
- [x] Clone your forked repo
- [x] Reply with an emoji by pressing the `:` key in a comment below :rocket:

**Comment by pixelyunicorn** [comment]
:eyes: :heart: :money_with_wings:

**Comment by MichaelGipson101** [comment]
You what mate?

**Comment by pixelyunicorn** [comment]
:moneybag: :moneybag: :moneybag: :yum:... :no_entry_sign: :monkey: :briefcase: :wink:!

![http://www.techranger.org/wp-content/uploads/2014/08/Obama-bucks-animated-money-gif1.gif](http://www.techranger.org/wp-content/uploads/2014/08/Obama-bucks-animated-money-gif1.gif)
